-- ================================================================
-- Teacher's Day Award Categories — FINAL PER-SCHOOL MODEL
--
-- Every election contains 9 award categories FOR EACH SCHOOL.
-- Students only see and can vote in the 9 categories belonging to
-- their own school.
--
-- This migration is intentionally self-contained. It works whether
-- the previous election-wide category migration has already been run
-- or not.
-- ================================================================

-- ---------------------------------------------------------------
-- 1) TABLES
-- ---------------------------------------------------------------
create table if not exists public.election_award_categories (
  id bigint generated by default as identity primary key,
  election_id bigint not null references public.elections(id) on delete cascade,
  school_id bigint references public.schools(id) on delete cascade,
  category_key text not null,
  category_name text not null,
  display_order integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint election_award_categories_display_order_check check (display_order > 0)
);

alter table public.election_award_categories
  add column if not exists school_id bigint references public.schools(id) on delete cascade;

create table if not exists public.category_votes (
  id bigint generated by default as identity primary key,
  election_id bigint not null references public.elections(id) on delete cascade,
  category_id bigint not null references public.election_award_categories(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  faculty_id bigint not null references public.faculty(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint category_votes_one_per_student_per_category
    unique (election_id, category_id, student_id)
);

-- ---------------------------------------------------------------
-- 2) REPLACE THE OLD ELECTION-WIDE CATEGORY UNIQUENESS
-- ---------------------------------------------------------------
alter table public.election_award_categories
  drop constraint if exists election_award_categories_unique_key;

-- ---------------------------------------------------------------
-- 3) SCHOOL-SPECIFIC CATEGORY SEEDING
-- ---------------------------------------------------------------
-- Use NOT EXISTS here because the school-specific unique constraint
-- is added after legacy rows are remapped and cleaned up. This also
-- makes the migration safe to re-run if the SQL editor partially
-- completed the earlier statements before an error occurred.
insert into public.election_award_categories
  (election_id, school_id, category_key, category_name, display_order, is_active)
select
  e.id,
  s.id,
  c.category_key,
  c.category_name,
  c.display_order,
  true
from public.elections e
cross join public.schools s
cross join (
  values
    ('funniest_teacher', 'Funniest Teacher', 1),
    ('most_inspiring_teacher', 'Most Inspiring Teacher', 2),
    ('best_dressed_teacher', 'Best Dressed Teacher', 3),
    ('most_approachable_teacher', 'Most Approachable Teacher Award', 4),
    ('most_energetic_teacher', 'Most Energetic Teacher Award', 5),
    ('most_punctual_teacher', 'Most Punctual Teacher Award', 6),
    ('human_google', 'Human Google Award', 7),
    ('most_updated_teacher', 'Most Updated Teacher Award', 8),
    ('teacher_of_the_year', 'Teacher of the Year', 9)
) as c(category_key, category_name, display_order)
where not exists (
  select 1
  from public.election_award_categories existing
  where existing.election_id = e.id
    and existing.school_id = s.id
    and existing.category_key = c.category_key
);

-- ---------------------------------------------------------------
-- 4) REMAP OLD ELECTION-WIDE CATEGORY VOTES
--
-- If the previous migration created election-wide category rows,
-- move those votes to the category belonging to the student's school.
-- ---------------------------------------------------------------
update public.category_votes cv
set category_id = target.id
from public.election_award_categories old_c,
     public.students st,
     public.programs pr,
     public.election_award_categories target
where old_c.id = cv.category_id
  and old_c.school_id is null
  and st.id = cv.student_id
  and pr.id = st.program_id
  and target.election_id = cv.election_id
  and target.school_id = pr.school_id
  and target.category_key = old_c.category_key
  and target.school_id is not null;

-- ---------------------------------------------------------------
-- 5) COPY LEGACY VOTES INTO SCHOOL-SPECIFIC TEACHER OF THE YEAR
-- ---------------------------------------------------------------
insert into public.category_votes
  (election_id, category_id, student_id, faculty_id, created_at)
select
  v.election_id,
  c.id,
  v.student_id,
  v.faculty_id,
  coalesce(v.created_at, now())
from public.votes v
join public.students st
  on st.id = v.student_id
join public.programs pr
  on pr.id = st.program_id
join public.election_award_categories c
  on c.election_id = v.election_id
 and c.school_id = pr.school_id
 and c.category_key = 'teacher_of_the_year'
where not exists (
  select 1
  from public.category_votes cv
  where cv.election_id = v.election_id
    and cv.category_id = c.id
    and cv.student_id = v.student_id
)
on conflict do nothing;

-- Remove obsolete election-wide category rows after their votes have
-- been remapped. Rows that still have category votes are preserved so
-- the migration never silently deletes vote history.
delete from public.election_award_categories old_c
where old_c.school_id is null
  and not exists (
    select 1
    from public.category_votes cv
    where cv.category_id = old_c.id
  );

-- If any null-school category still has votes, stop with a clear error
-- instead of failing later on the NOT NULL constraint.
do $check_null$
begin
  if exists (
    select 1
    from public.election_award_categories c
    where c.school_id is null
  ) then
    raise exception
      'Migration stopped: some legacy award categories still have no school_id. Review those rows before continuing.';
  end if;
end
$check_null$;

-- At this point all remaining categories are school-specific.
alter table public.election_award_categories
  alter column school_id set not null;

-- ---------------------------------------------------------------
-- 6) CONSTRAINTS + INDEXES
-- ---------------------------------------------------------------
do $constraint$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'election_award_categories_unique_school_key'
      and conrelid = 'public.election_award_categories'::regclass
  ) then
    alter table public.election_award_categories
      add constraint election_award_categories_unique_school_key
      unique (election_id, school_id, category_key);
  end if;
end
$constraint$;

create index if not exists idx_election_award_categories_election_school_order
  on public.election_award_categories (election_id, school_id, display_order);

create index if not exists idx_category_votes_election_category_faculty
  on public.category_votes (election_id, category_id, faculty_id);

create index if not exists idx_category_votes_election_category_student
  on public.category_votes (election_id, category_id, student_id);

create index if not exists idx_category_votes_student
  on public.category_votes (student_id);

-- ---------------------------------------------------------------
-- 7) RLS
-- ---------------------------------------------------------------
alter table public.election_award_categories enable row level security;
alter table public.category_votes enable row level security;

drop policy if exists "authenticated users can read election award categories"
  on public.election_award_categories;
create policy "authenticated users can read election award categories"
on public.election_award_categories
for select to authenticated
using (true);

-- No direct INSERT/UPDATE/DELETE policy on category_votes.
-- All writes happen through the security-definer RPC.

-- ---------------------------------------------------------------
-- 8) AUTO-SEED 9 CATEGORIES PER SCHOOL FOR NEW ELECTIONS
-- ---------------------------------------------------------------
drop trigger if exists trg_seed_election_award_categories on public.elections;
drop function if exists public.seed_election_award_categories();

create function public.seed_election_award_categories()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  insert into public.election_award_categories
    (election_id, school_id, category_key, category_name, display_order)
  select
    new.id,
    s.id,
    c.category_key,
    c.category_name,
    c.display_order
  from public.schools s
  cross join (
    values
      ('funniest_teacher', 'Funniest Teacher', 1),
      ('most_inspiring_teacher', 'Most Inspiring Teacher', 2),
      ('best_dressed_teacher', 'Best Dressed Teacher', 3),
      ('most_approachable_teacher', 'Most Approachable Teacher Award', 4),
      ('most_energetic_teacher', 'Most Energetic Teacher Award', 5),
      ('most_punctual_teacher', 'Most Punctual Teacher Award', 6),
      ('human_google', 'Human Google Award', 7),
      ('most_updated_teacher', 'Most Updated Teacher Award', 8),
      ('teacher_of_the_year', 'Teacher of the Year', 9)
  ) as c(category_key, category_name, display_order)
  on conflict (election_id, school_id, category_key) do nothing;

  return new;
end;
$function$;

create trigger trg_seed_election_award_categories
after insert on public.elections
for each row
execute function public.seed_election_award_categories();

-- ---------------------------------------------------------------
-- 9) STUDENT CATEGORY STATUS — ONLY THEIR SCHOOL
-- ---------------------------------------------------------------
drop function if exists public.get_student_category_statuses(bigint);
create function public.get_student_category_statuses(p_election_id bigint)
returns table (
  category_id bigint,
  category_name text,
  display_order integer,
  has_voted boolean
)
language sql
security definer
set search_path = public
as $$
  select
    c.id,
    c.category_name,
    c.display_order,
    exists (
      select 1
      from public.category_votes cv
      where cv.election_id = p_election_id
        and cv.category_id = c.id
        and cv.student_id = st.id
    ) as has_voted
  from public.election_award_categories c
  join public.students st
    on st.auth_user_id = (select auth.uid())
  join public.programs pr
    on pr.id = st.program_id
   and pr.school_id = c.school_id
  where c.election_id = p_election_id
    and c.is_active = true
  order by c.display_order;
$$;

revoke all on function public.get_student_category_statuses(bigint) from public;
revoke all on function public.get_student_category_statuses(bigint) from anon;
grant execute on function public.get_student_category_statuses(bigint) to authenticated;

-- ---------------------------------------------------------------
-- 10) CATEGORY VOTE SUBMISSION — SCHOOL-SCOPED + AUTHORITATIVE
-- ---------------------------------------------------------------
drop function if exists public.submit_category_vote(bigint, bigint, bigint);
create function public.submit_category_vote(
  p_election_id bigint,
  p_category_id bigint,
  p_faculty_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_uid uuid := (select auth.uid());
  v_student_id bigint;
  v_student_school_id bigint;
  v_election_status text;
  v_election_start timestamptz;
  v_election_end timestamptz;
  v_category_election_id bigint;
  v_category_school_id bigint;
  v_schedule_start timestamptz;
  v_schedule_end timestamptz;
  v_faculty_school_id bigint;
begin
  if v_uid is null then
    raise exception 'Authentication is required.';
  end if;

  select s.id, p.school_id
    into v_student_id, v_student_school_id
  from public.students s
  join public.programs p on p.id = s.program_id
  where s.auth_user_id = v_uid
  limit 1;

  if v_student_id is null then
    raise exception 'Student profile not found.';
  end if;

  select e.status, e.start_date, e.end_date
    into v_election_status, v_election_start, v_election_end
  from public.elections e
  where e.id = p_election_id;

  if v_election_status is null then
    raise exception 'Election not found.';
  end if;

  if v_election_status <> 'open' then
    raise exception 'This election is not open.';
  end if;

  if now() < v_election_start then
    raise exception 'The election has not started yet.';
  end if;

  if now() > v_election_end then
    raise exception 'The election has already ended.';
  end if;

  select c.election_id, c.school_id
    into v_category_election_id, v_category_school_id
  from public.election_award_categories c
  where c.id = p_category_id
    and c.is_active = true;

  if v_category_election_id is null or v_category_election_id <> p_election_id then
    raise exception 'Invalid award category for this election.';
  end if;

  if v_category_school_id <> v_student_school_id then
    raise exception 'This award category is not available for your school.';
  end if;

  select s.start_date, s.end_date
    into v_schedule_start, v_schedule_end
  from public.election_school_schedules s
  where s.election_id = p_election_id
    and s.school_id = v_student_school_id
  limit 1;

  if v_schedule_start is null or v_schedule_end is null then
    raise exception 'Voting for your school is not currently configured.';
  end if;

  if now() < v_schedule_start then
    raise exception 'Voting for your school has not started yet.';
  end if;

  if now() > v_schedule_end then
    raise exception 'Voting for your school has already ended.';
  end if;

  select f.school_id
    into v_faculty_school_id
  from public.faculty f
  where f.id = p_faculty_id;

  if v_faculty_school_id is null then
    raise exception 'Faculty member not found.';
  end if;

  if v_faculty_school_id <> v_student_school_id then
    raise exception 'You can only vote for faculty from your school.';
  end if;

  if exists (
    select 1
    from public.category_votes cv
    where cv.election_id = p_election_id
      and cv.category_id = p_category_id
      and cv.student_id = v_student_id
  ) then
    raise exception 'You have already voted in this award category.';
  end if;

  begin
    insert into public.category_votes
      (election_id, category_id, student_id, faculty_id)
    values
      (p_election_id, p_category_id, v_student_id, p_faculty_id);
  exception
    when unique_violation then
      raise exception 'You have already voted in this award category.';
  end;
end;
$function$;

revoke all on function public.submit_category_vote(bigint, bigint, bigint) from public;
revoke all on function public.submit_category_vote(bigint, bigint, bigint) from anon;
grant execute on function public.submit_category_vote(bigint, bigint, bigint) to authenticated;

-- ---------------------------------------------------------------
-- 11) ADMIN RESULTS — ONLY THE SCHOOL OWNING THE CATEGORY
-- ---------------------------------------------------------------
drop function if exists public.get_election_category_results(bigint, bigint);
create function public.get_election_category_results(
  p_election_id bigint,
  p_category_id bigint
)
returns table (
  school_code text,
  school_name text,
  logo_url text,
  faculty_id bigint,
  faculty_name text,
  program_name text,
  vote_count bigint
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_is_admin boolean;
  v_category_school_id bigint;
begin
  select public.is_admin() into v_is_admin;

  if not coalesce(v_is_admin, false) then
    raise exception 'Administrator privileges are required.';
  end if;

  select c.school_id
    into v_category_school_id
  from public.election_award_categories c
  where c.id = p_category_id
    and c.election_id = p_election_id
    and c.is_active = true;

  if v_category_school_id is null then
    raise exception 'Invalid award category for this election.';
  end if;

  return query
  select
    s.school_code,
    s.school_name,
    s.logo_url,
    f.id as faculty_id,
    f.name as faculty_name,
    coalesce(p.program_name, 'Program not listed') as program_name,
    count(cv.id)::bigint as vote_count
  from public.schools s
  join public.faculty f
    on f.school_id = s.id
  left join public.programs p
    on p.id = f.program_id
  left join public.category_votes cv
    on cv.election_id = p_election_id
   and cv.category_id = p_category_id
   and cv.faculty_id = f.id
  where s.id = v_category_school_id
  group by
    s.school_code,
    s.school_name,
    s.logo_url,
    f.id,
    f.name,
    p.program_name
  order by
    count(cv.id) desc,
    f.name;
end;
$function$;

revoke all on function public.get_election_category_results(bigint, bigint) from public;
revoke all on function public.get_election_category_results(bigint, bigint) from anon;
grant execute on function public.get_election_category_results(bigint, bigint) to authenticated;

-- ---------------------------------------------------------------
-- 12) LEGACY SUBMIT_VOTE WRAPPER — SCHOOL-SPECIFIC T.O.Y.
-- ---------------------------------------------------------------
create or replace function public.submit_vote(p_election_id bigint, p_faculty_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_uid uuid := (select auth.uid());
  v_student_school_id bigint;
  v_category_id bigint;
begin
  select p.school_id
    into v_student_school_id
  from public.students s
  join public.programs p on p.id = s.program_id
  where s.auth_user_id = v_uid
  limit 1;

  if v_student_school_id is null then
    raise exception 'Student profile not found.';
  end if;

  select c.id
    into v_category_id
  from public.election_award_categories c
  where c.election_id = p_election_id
    and c.school_id = v_student_school_id
    and c.category_key = 'teacher_of_the_year'
    and c.is_active = true
  limit 1;

  if v_category_id is null then
    raise exception 'Teacher of the Year category is not configured for your school.';
  end if;

  perform public.submit_category_vote(
    p_election_id,
    v_category_id,
    p_faculty_id
  );
end;
$function$;

revoke all on function public.submit_vote(bigint, bigint) from public;
revoke all on function public.submit_vote(bigint, bigint) from anon;
grant execute on function public.submit_vote(bigint, bigint) to authenticated;
